/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useSphere } from "@react-three/cannon";
import { useDragConstraint } from "../drag/Drag";

export default function Baseball({ setToggleOrbit }) {
  const group = useRef();
  const [ref, api] = useSphere(() => ({
    mass: 1000,
    position: [-10, 10, 10],
    // args: [4],
    scale: 20,
    color: "#333",
  }));
  const bind = useDragConstraint(ref, setToggleOrbit);

  const { nodes, materials } = useGLTF(
    "/baseball/baseball_01_4k.gltf/baseball_01_4k.gltf"
  );

  return (
    <group ref={ref} {...bind} dispose={null} >
      <mesh
        scale={20}
        geometry={nodes.baseball_01.geometry}
        material={materials.baseball_01}
      />
    </group>
  );
}

useGLTF.preload("/baseball/baseball_01_4k.gltf/baseball_01_4k.gltf");
