/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {usePlane} from '@react-three/cannon'


export default function Floor({ ...props }) {
  const [ref] = usePlane(() => ({ rotation: [-Math.PI / 2, 0, 0], position: [0, 0, 0], mass: 0, type: 'Static' }));
  const { nodes, materials } = useGLTF('/tiled_floor_001_4k.gltf/tiled_floor_001_4k.gltf')
  return (
    <group  {...props} dispose={null}>
      <mesh ref={ref} material={materials.tiled_floor_001} >
        <planeGeometry args={[100, 100]} />
        <meshPhongMaterial attatch="material" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/tiled_floor_001_4k.gltf/tiled_floor_001_4k.gltf')
